# mysql
- name: mysql is installed
  sudo: yes
  yum: pkg={{ item }} state=installed
  with_items:
    - mariadb-server
    - mariadb-devel
  tags: mysqld

- name: mysqld is running and enabled
  sudo: yes
  service: name=mariadb state=running enabled=yes
  tags: mysqld
